using UnityEngine;
using System.Collections.Generic;
using System.Collections;
using Assets.Scripts.Game.Maze;

namespace Assets.Scripts.Game.MeshGenerators
{
    class StandardMeshGenerator: MeshGeneratorBase
    {

        #region Fields

        private Mesh mesh;
        private Vector3[] _vertices;
        private int[] _triangles;

        #endregion

        #region Properties
            
        #endregion

        #region Constructors

        #endregion


        #region Concrete methods

        public override Mesh GenerateMesh(MazeDescription description)
        {
            mesh = new Mesh();
            List<Vector3> verticesList = new List<Vector3>(mesh.vertices);
            List<int> trianglesList = new List<int>(mesh.triangles);
            List<Vector2> uvList = new List<Vector2>(mesh.uv);

            CellMesh c1 = new CellMesh();
            CellMesh c2 = new CellMesh(1.0f, 0.0f);
            verticesList.AddRange(c1.Mesh.vertices);
            trianglesList.AddRange(c1.Mesh.triangles);
            uvList.AddRange(c1.Mesh.uv);
            
            List<int> c2l = new List<int>(c2.Mesh.triangles);
            c2l = c2l.ConvertAll<int>(x => x = x + verticesList.Count);
            verticesList.AddRange(c2.Mesh.vertices);
            trianglesList.AddRange(c2l);
            uvList.AddRange(c2.Mesh.uv);
            
            mesh.vertices = verticesList.ToArray();
            mesh.triangles = trianglesList.ToArray();
            mesh.uv = uvList.ToArray();

            mesh.RecalculateNormals();

            Debug.Log("Mesh generated by test mesh generator");
            return mesh;
        }

        #endregion
    }
}
